config/routes.rb
Rails.application.routes.draw do
  resources :docs, only: [:index, :new, :create]
   root to: "docs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/doc.rb
class Doc < ApplicationRecord

  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true # Make sure the owner's name is present.
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  def index
    @docs = Doc.all
  end

  def show
   
  end

  def new
    @doc = Doc.new
  end

  def create
    @doc = Doc.new(doc_params)

    respond_to do |format|
      format.html do
        if @doc.save
          redirect_to docs_path
        else
          redirect_to new_doc_path
        end
      end
    end

  end

  private
  def doc_params
    params.require(:doc).permit(:name, :attachment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/views/docs/create.html.erb
<h1>Docs#create</h1>
<p>Find me in app/views/docs/create.html.erb</p>

app/views/docs/index.html.erb
<%= link_to "Add Pdf", new_doc_path %>

<div>
      <% @docs.each do |doc| %>  
      <span><h2><%= doc.name %></h2><span>
      <span> <%= link_to "Open pdf", doc.attachment_url %></span>
      <% end %>
</div>
  
   

app/views/docs/new.html.erb
<%= form_with model: @doc, url: docs_url, method: :post do |form| %>
 <%= form.label :name, 'Name' %>
    <%= form.text_field :name %>
    <%= form.label :text, 'Attachment' %>
    <%= form.file_field :attachment %>
    <%= form.submit 'Post' %>
<%end%>

app/views/docs/show.html.erb
<h1>Docs#show</h1>
<p>Find me in app/views/docs/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoutingConcepts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>